3.3.1 生成数据集

In [1]:
import numpy as np
import torch
from torch.utils import data
from d2l import torch as d2l

In [7]:
true_w = torch.tensor([2, -3.4])
true_b = 4.2
features, labels = d2l.synthetic_data(true_w, true_b, 1000)
print(features)
print(labels)

tensor([[ 0.7173,  0.7583],
        [ 1.1007,  0.5352],
        [-0.8611, -0.0375],
        ...,
        [ 0.2223,  1.3597],
        [ 1.3063, -0.4174],
        [ 1.0749, -1.0949]])
tensor([[ 3.0599e+00],
        [ 4.5867e+00],
        [ 2.6151e+00],
        [ 5.1275e+00],
        [ 1.1291e+01],
        [ 5.7596e+00],
        [ 8.0345e-04],
        [ 4.0284e+00],
        [ 3.8772e+00],
        [ 3.0994e+00],
        [ 8.0948e+00],
        [ 3.5733e+00],
        [ 1.9908e+00],
        [ 5.3203e+00],
        [ 4.6708e-01],
        [ 6.4515e+00],
        [ 1.5556e+00],
        [-6.0670e-01],
        [-3.3489e-01],
        [ 7.1978e+00],
        [-1.6912e-01],
        [ 7.1372e+00],
        [ 4.7566e+00],
        [-2.1669e+00],
        [ 1.9567e+00],
        [ 6.3283e+00],
        [ 4.7597e+00],
        [ 2.6360e+00],
        [ 2.2229e+00],
        [ 7.2789e+00],
        [ 3.9220e+00],
        [ 9.9494e-01],
        [ 1.6986e+00],
        [-1.7279e+00],
        [ 9.2987e+00],
        [ 5.4

3.3.2 读取数据集

In [3]:
def load_array(data_arrays, batch_size, is_train=True): #@save
    """构造一个Pytorch数据迭代器"""
    dataset = data.TensorDataset(*data_arrays)
    return data.DataLoader(dataset, batch_size, shuffle=is_train)

In [4]:
batch_size = 10
data_iter = load_array((features, labels), batch_size)

In [5]:
next(iter(data_iter))

[tensor([[-0.4834, -0.3032],
         [-0.1507, -1.4929],
         [ 0.5613, -0.8180],
         [ 0.5218, -1.1432],
         [-1.6574,  0.9316],
         [ 0.4907, -0.2098],
         [-0.9334, -0.5559],
         [ 0.3813,  0.3374],
         [-0.5492, -1.1152],
         [ 1.5576,  0.4196]]),
 tensor([[ 4.2558],
         [ 8.9888],
         [ 8.1072],
         [ 9.1154],
         [-2.2796],
         [ 5.8862],
         [ 4.2243],
         [ 3.8034],
         [ 6.8923],
         [ 5.8813]])]

3.3.3 定义模型

In [8]:
# nn是神经网络的缩写
from torch import nn

net = nn.Sequential(nn.Linear(2, 1))

In [9]:
net[0].weight.data.normal_(0, 0.01)
net[0].bias.data.fill_(0)

tensor([0.])

3.3.5 定义损失函数

In [10]:
loss = nn.MSELoss()

3.3.6 定义优化算法

In [11]:
trainer = torch.optim.SGD(net.parameters(), lr=0.03)

3.3.7 训练

In [12]:
num_epochs = 3
for epoch in range(num_epochs):
    for X, y in data_iter:
        l = loss(net(X), y)
        trainer.zero_grad()
        l.backward()
        trainer.step()
    l = loss(net(features), labels)
    print(f'epoch {epoch + 1}, loss {l:f}')

epoch 1, loss 0.000454
epoch 2, loss 0.000108
epoch 3, loss 0.000107


In [13]:
w = net[0].weight.data
print('w的估计误差：', true_w - w.reshape(true_w.shape))
b = net[0].bias.data
print('b的估计误差：', true_b - b)

w的估计误差： tensor([0.0006, 0.0006])
b的估计误差： tensor([0.0011])
