In [14]:
import torch
from torch import nn

torch.device('cpu'), torch.cuda.device('cuda')

(device(type='cpu'), <torch.cuda.device at 0x267591b7e50>)

In [2]:
torch.cuda.device_count()

1

In [3]:
x = torch.tensor([1, 2, 3])
x.device

device(type='cpu')

In [5]:
x = torch.ones(2, 3, device='cuda')
x

tensor([[1., 1., 1.],
        [1., 1., 1.]], device='cuda:0')

In [6]:
y = torch.rand(2, 3, device='cuda')
y

tensor([[0.0366, 0.9303, 0.8332],
        [0.9636, 0.0657, 0.2006]], device='cuda:0')

In [7]:
x + y

tensor([[1.0366, 1.9303, 1.8332],
        [1.9636, 1.0657, 1.2006]], device='cuda:0')

In [8]:
x.cuda(0) is x

True

In [15]:
net = nn.Sequential(nn.Linear(3, 1))
net = net.to('cuda')

net(x)

tensor([[0.0997],
        [0.0997]], device='cuda:0', grad_fn=<AddmmBackward0>)

In [16]:
net[0].weight.data.device

device(type='cuda', index=0)