2.1.1 入门

In [1]:
import torch

In [2]:
# 创建一个行向量
x = torch.arange(12)
x

tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [3]:
# 访问张量的形状
x.shape

torch.Size([12])

In [4]:
# 计算张量中元素的总数
x.numel()

12

In [5]:
# 设置行列
X = x.reshape(3,4)
X

tensor([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]])

In [6]:
# 输入列自动改变行
x.reshape(-1,4)

tensor([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]])

In [7]:
# 输入行自动改变列
x.reshape(3,-1)

tensor([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]])

In [8]:
# 生成全0
torch.zeros(2,3,4)

tensor([[[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]])

In [9]:
# 生成全1
torch.ones(2,3,4)

tensor([[[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]],

        [[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]]])

In [10]:
# 随机生成一个形状为（3,4）的张量，每个元素都从均值为0，标准差为1的标准高斯分布（正态分布）
torch.randn(3,4)

tensor([[ 0.1147,  0.6845, -2.0172,  0.2295],
        [ 1.9295, -0.6298, -0.3968, -0.0163],
        [-0.6147, -1.2477, -0.5414, -0.2714]])

In [11]:
# 生成指定形状的张量
torch.tensor(([2,1,4,3],[1,2,3,4],[4,3,2,1]))

tensor([[2, 1, 4, 3],
        [1, 2, 3, 4],
        [4, 3, 2, 1]])

2.1.2 运算符

In [12]:
# 运算符
x = torch.tensor([1.0,2,4,8])
y = torch.tensor([2,2,2,2])
x + y,x - y, x * y, x / y, x ** y

(tensor([ 3.,  4.,  6., 10.]),
 tensor([-1.,  0.,  2.,  6.]),
 tensor([ 2.,  4.,  8., 16.]),
 tensor([0.5000, 1.0000, 2.0000, 4.0000]),
 tensor([ 1.,  4., 16., 64.]))

In [13]:
# 求幂运算（e^x）
torch.exp(x)

tensor([2.7183e+00, 7.3891e+00, 5.4598e+01, 2.9810e+03])

In [14]:
# 张量连接[按行输出(轴0)，按列输出（轴1）]
x = torch.arange(12,dtype=torch.float32).reshape((3,4))
y = torch.tensor([[2.0,1,4,3],[1,2,3,4],[4,3,2,1]])
x,y,torch.cat((x,y), dim=0), torch.cat((x,y), dim=1)

(tensor([[ 0.,  1.,  2.,  3.],
         [ 4.,  5.,  6.,  7.],
         [ 8.,  9., 10., 11.]]),
 tensor([[2., 1., 4., 3.],
         [1., 2., 3., 4.],
         [4., 3., 2., 1.]]),
 tensor([[ 0.,  1.,  2.,  3.],
         [ 4.,  5.,  6.,  7.],
         [ 8.,  9., 10., 11.],
         [ 2.,  1.,  4.,  3.],
         [ 1.,  2.,  3.,  4.],
         [ 4.,  3.,  2.,  1.]]),
 tensor([[ 0.,  1.,  2.,  3.,  2.,  1.,  4.,  3.],
         [ 4.,  5.,  6.,  7.,  1.,  2.,  3.,  4.],
         [ 8.,  9., 10., 11.,  4.,  3.,  2.,  1.]]))

In [15]:
# 逻辑运算构建二元张量
x == y

tensor([[False,  True, False,  True],
        [False, False, False, False],
        [False, False, False, False]])

In [16]:
x < y, x > y

(tensor([[ True, False,  True, False],
         [False, False, False, False],
         [False, False, False, False]]),
 tensor([[False, False, False, False],
         [ True,  True,  True,  True],
         [ True,  True,  True,  True]]))

In [17]:
# 对张量中所有元素求和
x.sum()

tensor(66.)

2.1.3 广播机制

In [18]:
# 大多数情况是按照数组中长度为1的轴进行广播
a = torch.arange(3).reshape((3,1))
b = torch.arange(2).reshape((1,2))
a,b

(tensor([[0],
         [1],
         [2]]),
 tensor([[0, 1]]))

In [19]:
a + b

tensor([[0, 1],
        [1, 2],
        [2, 3]])

In [20]:
a = torch.arange(8).reshape((8,1,1))
b = torch.arange(4).reshape((1,4))
a, b

(tensor([[[0]],
 
         [[1]],
 
         [[2]],
 
         [[3]],
 
         [[4]],
 
         [[5]],
 
         [[6]],
 
         [[7]]]),
 tensor([[0, 1, 2, 3]]))

In [21]:
a + b

tensor([[[ 0,  1,  2,  3]],

        [[ 1,  2,  3,  4]],

        [[ 2,  3,  4,  5]],

        [[ 3,  4,  5,  6]],

        [[ 4,  5,  6,  7]],

        [[ 5,  6,  7,  8]],

        [[ 6,  7,  8,  9]],

        [[ 7,  8,  9, 10]]])

2.1.4 索引和切片

In [22]:
# [-1]选择最后一个， [1,3]选择第二个和第三个
x[-1],x[1:3]

(tensor([ 8.,  9., 10., 11.]),
 tensor([[ 4.,  5.,  6.,  7.],
         [ 8.,  9., 10., 11.]]))

In [23]:
# 将元素写入矩阵
x[1,2] = 9
x

tensor([[ 0.,  1.,  2.,  3.],
        [ 4.,  5.,  9.,  7.],
        [ 8.,  9., 10., 11.]])

In [24]:
# 同时为多个元素赋相同的值
x[0:2,:] = 12
x

tensor([[12., 12., 12., 12.],
        [12., 12., 12., 12.],
        [ 8.,  9., 10., 11.]])

2.1.4 节省内存

In [25]:
# 用Python的id()函数提供了内存中引用对象的确切地址。
# 运行Y = Y + X后，我们会发现id(Y)指向另一个位置。 
# 这是因为Python首先计算Y + X，为结果分配新的内存，然后使Y指向内存中的这个新位置
before = id(y)
y = y + x
id(y) == before

False

In [26]:
# 原地操作（使用切片表示法:Y[:] = <expression>）
z = torch.zeros_like(y)
print('id(z):', id(z))
z[:] = x + y
print('id(z):', id(z))


id(z): 2049934648880
id(z): 2049934648880


In [27]:
# 如果没有重复使用X， 我们也可以使用X[:] = X + Y或X += Y来减少操作的内存开销
before = id(x)
x += y
id(x) == before

True

2.1.6 转换为其他Python对象

In [28]:
A = x.numpy()
B = torch.tensor(A)
type(A),type(B)

(numpy.ndarray, torch.Tensor)

In [29]:
a = torch.tensor([3.5])
a, a.item(), float(a), int(a)

(tensor([3.5000]), 3.5, 3.5, 3)